### ISSUE TITLE
DICUI silently dies when drive firmware update is required

### ISSUE THREAD

**Issue by hughesw** [reignstumble/DICUI#96] opened 2018-07-14 20:12 UTC
I just grabbed DICUI to dump a disc using my PX716A, which was running firmware 1.07. When this drive is connected, DICUI just silently dies and plays the fail tones that DiscImageCreator.exe plays when you run it without arguments. I wasn't sure what was going on, so I ran the command to dump manually using the program in the Programs folder, and I saw exactly what was going on:

DiscImageCreator.exe returns this:
DiscImageCreator.exe cd h "image.bin" 24 /c2 /nl
AppVersion
        x86, AnsiBuild, 20180619 20619
/c2 val1 is omitted. set [4000]
/c2 val2 is omitted. set [0]
CurrentDirectory
        C:\Applications\DiscImageCreator\Programs
WorkingPath
         Argument: image.bin
         FullPath: C:\Applications\DiscImageCreator\Programs\image
            Drive: C:
        Directory: \Applications\DiscImageCreator\Programs\
         Filename: image
        Extension: .bin
StartTime: 2018/07/14(Sat) 13:02:04
[ERROR] This drive isn't latest firmware. Please update.
EndTime: 2018/07/14(Sat) 13:02:04

This error is being silently dropped by DICUI, not even running it via command line shows it. After I updated the drive to 1.11 firmware, DICUI now starts up correctly.

**Comment by mnadareski** [comment] 2018-07-16 03:08
Please try the newest Git builds, this should have already been addressed.

**Comment by mnadareski** [comment] 2018-07-16 07:07
Duplicate of #81

**Closed** 2018-07-24 17:04 UTC
Labels: duplicate, wontfix
